// Generated by CoffeeScript 1.3.3
(function() {
  var st_root_post,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  st_root_post = (function() {

    function st_root_post(root_node) {
      this.mutated = __bind(this.mutated, this);
      this.wrapped_root_node = $(root_node);
      this.observer = new MutationObserver(this.mutated);
      this.observer.observe(this.wrapped_root_node, {
        childList: true,
        subtree: true
      });
    }

    st_root_post.prototype.mutated = function(mutation_records, observer) {
      return alert(mutation_records.length);
    };

    return st_root_post;

  })();

}).call(this);
